// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Measurement struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	MeasurementDate time.Time
	MeasurementTime time.Time
	Pressure1       float64
	Pressure2       float64
	Temperature1    float64
	Temperature2    float64
}
