// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Measurement struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	MeasurementDate time.Time
	MeasurementTime time.Time
	Pressure1       string
	Pressure2       string
	Temperature1    string
	Temperature2    string
}
